# Generated by Django 5.2.3 on 2025-07-10 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('port_id', models.AutoField(primary_key=True, serialize=False)),
                ('port_name', models.CharField(max_length=100)),
                ('port_code', models.CharField(max_length=10, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('port_description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('vessel_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('imo', models.CharField(max_length=20, unique=True)),
                ('vessel_type', models.CharField(choices=[('container', 'Container'), ('ro_ro', 'Ro-Ro'), ('general_cargo', 'General Cargo')], default='general_cargo', max_length=30)),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('maintenance', 'Under Maintenance')], default='available', max_length=20)),
                ('capacity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vessels', to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('activity_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('assigned', 'Assigned'), ('status_update', 'Status Update'), ('delayed', 'Delayed'), ('arrived', 'Arrived'), ('note', 'Manual Note'), ('created', 'Created')], max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='accounts.userprofile')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='smartportApp.vessel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('voyage_id', models.AutoField(primary_key=True, serialize=False)),
                ('departure_date', models.DateTimeField()),
                ('eta', models.DateTimeField(blank=True, null=True)),
                ('arrival_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('arrived', 'Arrived'), ('in_transit', 'In Transit'), ('assigned', 'Assigned'), ('delayed', 'Delayed')], default='assigned', max_length=20)),
                ('voyage_number', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arrival_port', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrivals', to='smartportApp.port')),
                ('departure_port', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departures', to='smartportApp.port')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyages', to='smartportApp.vessel')),
            ],
        ),
        migrations.CreateModel(
            name='VoyageReport',
            fields=[
                ('voyage_report_id', models.AutoField(primary_key=True, serialize=False)),
                ('voyage_report', models.TextField()),
                ('delayed_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voyage_reports', to='accounts.userprofile')),
                ('voyage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='smartportApp.voyage')),
            ],
        ),
    ]
