# Generated by Django 5.2.3 on 2025-07-03 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('port_id', models.AutoField(primary_key=True, serialize=False)),
                ('port_name', models.CharField(max_length=100)),
                ('port_code', models.CharField(max_length=10, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('port_description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('vessel_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('imo', models.CharField(max_length=20, unique=True)),
                ('vessel_type', models.CharField(choices=[('container', 'Container'), ('ro_ro', 'Ro-Ro'), ('general_cargo', 'General Cargo')], default='general_cargo', max_length=30)),
                ('status', models.CharField(choices=[('arrived', 'Arrived'), ('in_transit', 'In Transit'), ('maintenance', 'Under Maintenance'), ('delayed', 'Delayed')], default='in_transit', max_length=20)),
                ('capacity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vessels', to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('voyage_id', models.AutoField(primary_key=True, serialize=False)),
                ('departure_date', models.DateTimeField()),
                ('eta', models.DateTimeField(blank=True, null=True)),
                ('arrival_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('arrived', 'Arrived'), ('in_transit', 'In Transit'), ('maintenance', 'Under Maintenance'), ('delayed', 'Delayed')], default='in_transit', max_length=20)),
                ('voyage_number', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arrival_port', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrivals', to='smartportApp.port')),
                ('departure_port', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departures', to='smartportApp.port')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyages', to='smartportApp.vessel')),
            ],
        ),
    ]
