# Generated by Django 5.2.3 on 2025-07-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartportApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('maintenance', 'Under Maintenance')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='status',
            field=models.CharField(choices=[('arrived', 'Arrived'), ('in_transit', 'In Transit'), ('delayed', 'Delayed')], default='in_transit', max_length=20),
        ),
    ]
