# Generated by Django 5.2.3 on 2025-07-17 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('smartportApp', '0002_submanifest_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submanifest',
            name='bill_of_lading_no',
            field=models.CharField(max_length=17),
        ),
        migrations.AlterField(
            model_name='submanifest',
            name='container_no',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='submanifest',
            name='seal_no',
            field=models.CharField(max_length=15),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('link_url', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to='accounts.userprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
