# Generated by Django 5.2.3 on 2025-07-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartportApp', '0002_incidentreport_incidentimage_incidentresolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
