# Generated by Django 5.2.3 on 2025-07-05 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartportApp', '0002_alter_vessel_status_alter_voyage_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoyageReport',
            fields=[
                ('voyage_report_id', models.AutoField(primary_key=True, serialize=False)),
                ('voyage_report', models.TextField()),
                ('voyage_number', models.CharField(max_length=50)),
                ('created_by', models.IntegerField()),
                ('delayed_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
