# Generated by Django 5.2.3 on 2025-07-16 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('smartportApp', '0003_incidentreport_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('status_update', 'Status Update'), ('delayed', 'Delayed'), ('arrived', 'Arrived'), ('note', 'Manual Note'), ('created', 'Created'), ('incident', 'Incident')], max_length=20),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='incident_type',
            field=models.CharField(choices=[('oil_spill', 'Oil Spill'), ('collision', 'Collision'), ('grounding', 'Grounding'), ('fire', 'Fire'), ('capsizing', 'Capsizing'), ('slip_trip_fall', 'Slip, Trip, or Fall'), ('human_error', 'Human Error'), ('other', 'Other')], max_length=30),
        ),
        migrations.CreateModel(
            name='MasterManifest',
            fields=[
                ('mastermanifest_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('finalized', 'Finalized')], default='generated', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userprofile')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartportApp.vessel')),
                ('voyage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='master_manifest', to='smartportApp.voyage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubManifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignee_name', models.CharField(max_length=255)),
                ('consignee_email', models.EmailField(max_length=254)),
                ('consignee_address', models.TextField()),
                ('consignor_name', models.CharField(max_length=255)),
                ('consignor_email', models.EmailField(max_length=254)),
                ('consignor_address', models.TextField()),
                ('container_no', models.CharField(max_length=100)),
                ('seal_no', models.CharField(max_length=100)),
                ('bill_of_lading_no', models.CharField(max_length=100)),
                ('handling_instruction', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending_admin', 'Pending Admin Review'), ('rejected_by_admin', 'Rejected by Admin'), ('pending_customs', 'Pending Customs Review'), ('rejected_by_customs', 'Rejected by Customs'), ('approved', 'Approved')], default='pending_admin', max_length=30)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('customs_note', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userprofile')),
                ('master_manifest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartportApp.mastermanifest')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_submanifests', to='accounts.userprofile')),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartportApp.voyage')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('bill_of_lading', 'Bill of Lading'), ('invoice', 'Invoice'), ('packing_list', 'Packing List'), ('other', 'Other')], max_length=50)),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('custom_filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userprofile')),
                ('submanifest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='smartportApp.submanifest')),
            ],
        ),
    ]
