# Generated by Django 5.2.3 on 2025-07-05 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('smartportApp', '0003_voyagereport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voyagereport',
            name='voyage_number',
        ),
        migrations.AddField(
            model_name='voyagereport',
            name='voyage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='smartportApp.voyage'),
        ),
        migrations.AlterField(
            model_name='voyagereport',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voyage_reports', to='accounts.userprofile'),
        ),
    ]
