# Generated by Django 5.2.3 on 2025-07-08 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('smartportApp', '0004_remove_voyagereport_voyage_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('activity_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('assigned', 'Assigned'), ('status_update', 'Status Update'), ('delayed', 'Delayed'), ('arrived', 'Arrived'), ('note', 'Manual Note')], max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='accounts.userprofile')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='smartportApp.vessel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
