# Generated by Django 5.2.3 on 2025-07-10 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartportApp', '0005_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('status_update', 'Status Update'), ('delayed', 'Delayed'), ('arrived', 'Arrived'), ('note', 'Manual Note'), ('created', 'Created')], max_length=20),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='status',
            field=models.CharField(choices=[('arrived', 'Arrived'), ('in_transit', 'In Transit'), ('assigned', 'Assigned'), ('delayed', 'Delayed')], default='assigned', max_length=20),
        ),
    ]
