# Generated by Django 5.2.3 on 2025-07-21 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartportApp', '0005_mastermanifest_submanifest_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mastermanifest',
            old_name='submanifest_number',
            new_name='mastermanifest_number',
        ),
    ]
