# Generated by Django 5.2.3 on 2025-07-21 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartportApp', '0006_rename_submanifest_number_mastermanifest_mastermanifest_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='submanifest',
            name='admin_rejection_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submanifest',
            name='customs_rejection_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
