# Generated by Django 5.2.3 on 2025-07-25 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('smartportApp', '0007_submanifest_admin_rejection_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoDelivery',
            fields=[
                ('cargo_delivery_id', models.AutoField(primary_key=True, serialize=False)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('cargo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='smartportApp.cargo')),
                ('confirmed_by', models.ForeignKey(limit_choices_to={'role': 'shipper'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userprofile')),
            ],
        ),
    ]
