# Generated by Django 5.2.3 on 2025-07-26 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('smartportApp', '0008_cargodelivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomClearance',
            fields=[
                ('clearance_id', models.AutoField(primary_key=True, serialize=False)),
                ('clearance_status', models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('inspection_date', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('clearance_file', models.FileField(blank=True, null=True, upload_to='custom_clearances/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clearances', to='accounts.userprofile')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_clearances', to='accounts.userprofile')),
                ('submanifest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_clearance', to='smartportApp.submanifest')),
            ],
        ),
    ]
