# Generated by Django 5.2.3 on 2025-07-26 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartportApp', '0009_customclearance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customclearance',
            name='clearance_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('cleared', 'Cleared'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
