# Generated by Django 5.2.3 on 2025-08-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartportApp', '0010_alter_customclearance_clearance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('bill_of_lading', 'Bill of Lading'), ('invoice', 'Invoice'), ('packing_list', 'Packing List'), ('certificate_of_origin', 'Certificate Of Origin'), ('other', 'Other')], max_length=50),
        ),
    ]
