# Generated by Django 5.2.3 on 2025-08-05 07:33

import smartportApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartportApp', '0011_alter_document_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=smartportApp.models.document_upload_path),
        ),
    ]
