# Generated by Django 5.2.3 on 2025-08-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartportApp', '0012_document_original_filename_alter_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='customclearance',
            name='clearance_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
